#!/usr/bin/env bash
# Minimal nvcc stub that writes a placeholder PTX at the path provided with -o.
# This allows building and running CPU-only tests while CUDA device tests skip.

set -euo pipefail

out=""
src=""
arch="compute_80"
while [[ $# -gt 0 ]]; do
  case "$1" in
    -o)
      out="$2"; shift 2 ;;
    -arch)
      arch="$2"; shift 2 ;;
    *)
      # record last non-flag as src candidate
      if [[ "$1" == *.cu ]]; then src="$1"; fi
      shift ;;
  esac
done

if [[ -z "${out}" ]]; then
  echo "nvcc_stub: no -o path provided" 1>&2
  exit 1
fi

mkdir -p "$(dirname "$out")"
cat > "$out" <<PTX
// placeholder PTX generated by nvcc_stub.sh (no-op kernels)
.version 7.5
.target sm_80
.address_size 64

.visible .entry chande_batch_f32() { ret; }
.visible .entry chande_many_series_one_param_f32() { ret; }
.visible .entry atr_batch_f32() { ret; }
.visible .entry atr_batch_from_tr_prefix_f32() { ret; }
.visible .entry atr_many_series_one_param_f32() { ret; }
PTX

echo "nvcc_stub: wrote placeholder PTX to $out (src=$src)" 1>&2
exit 0
