#!/usr/bin/env bash



set -euo pipefail

out=""
src=""
arch="compute_80"
while [[ $
  case "$1" in
    -o)
      out="$2"; shift 2 ;;
    -arch)
      arch="$2"; shift 2 ;;
    *)

      if [[ "$1" == *.cu ]]; then src="$1"; fi
      shift ;;
  esac
done

if [[ -z "${out}" ]]; then
  echo "nvcc_stub: no -o path provided" 1>&2
  exit 1
fi

mkdir -p "$(dirname "$out")"
cat > "$out" <<PTX
// placeholder PTX generated by nvcc_stub.sh (no-op kernels)
.version 7.5
.target sm_80
.address_size 64

.visible .entry ao_batch_f32(
    .param .u64 prefix_ds,
    .param .s32 len,
    .param .s32 first_valid,
    .param .u64 shorts,
    .param .u64 longs,
    .param .s32 n_combos,
    .param .u64 out_ptr
) { ret; }

.visible .entry ao_many_series_one_param_f32(
    .param .u64 prices_tm,
    .param .u64 first_valids,
    .param .s32 num_series,
    .param .s32 series_len,
    .param .s32 short_p,
    .param .s32 long_p,
    .param .u64 out_tm
) { ret; }

.visible .entry chande_batch_f32() { ret; }
.visible .entry chande_many_series_one_param_f32() { ret; }
.visible .entry atr_batch_f32() { ret; }
.visible .entry atr_batch_from_tr_prefix_f32() { ret; }
.visible .entry atr_many_series_one_param_f32() { ret; }
PTX

echo "nvcc_stub: wrote placeholder PTX to $out (src=$src)" 1>&2
exit 0
